### ISSUE TITLE
MongoDB supports ?

### ISSUE THREAD

**Issue by folkevil** [Mahmoudz/Hello-API#37]
Hello Mahmoudz,
I'm planning to use Hello API and jenssegers/laravel-mongodb for my next project, but in document Hello API required 

> All Models MUST extend from App\Port\Model\Abstracts\Model

Do you have any suggest ?
One more thing, when i'm testing latest version i got this error:

`{
message: "Class 'App\Port\Controller\Abstracts\KernelWebController' not found",
code: 1,
status_code: 500
}`

**Comment by Mahmoudz** [comment]
Hi folkevil,
That's easy, the only change you need to do is go to `app/Port/Model/Abstracts/Model.php` and make the class extend from your Package `Mongo Abstract Class` instead of `LaravelEloquentModel`.

Then let all you Models extend from `App\Port\Model\Abstracts\Model` normally.

You need to pull the latest master branch. That's an old file `KernelWebController` it was renamed to `PortWebController` (`app/Port/Controller/Abstracts/PortWebController.php`).

Thanks for using Hello API.

**Comment by folkevil** [comment]
Thanks dude,
And i think you should add a comment to public/.htaccess 

> #RewriteEngine On if Apache2

At first time i can't test api because RewriteKernel is not working on Apache2/windows

**Comment by Mahmoudz** [comment]
Cool, thanks for you. Could you make a quick PR with that?

**Comment by Mahmoudz** [comment]
I was able to reproduce your error after cloning a fresh copy of Hello API and was fixed in #84a416d740f600f63f27c286ed866bd7f6c6d81c

**Comment by bencagri** [comment]
hello, what is the implementation for latest tag?
