### ISSUE TITLE
DATABASE_QUERIES_DEBUG true error

### ISSUE THREAD

**Issue by luciano-jr** [Mahmoudz/Hello-API#46]
When I ran `php artisan migrate` I received that exception. If I change `DATABASE_QUERIES_DEBUG` to false the error does not appear 

[ErrorException]                                                                                              
Missing argument 2 for App\Port\Provider\Providers\PortServiceProvider::App\Port\Provider\Traits\{closure}()

**Comment by Mahmoudz** [comment]
Hi, I assume you upgrading after using an older version, that's why you are facing this error. 
I've added a second parameter to the function `debugDatabaseQueries`. It looks like this now:

```php
    public function debugDatabaseQueries($log = true, $terminal = false)
    {
        if (Config::get('database.query_debugging')) {

            DB::listen(function ($query, $bindings, $time, $connection) use ($terminal, $log) {
                $fullQuery = vsprintf(str_replace(['%', '?'], ['%%', '%s'], $query), $bindings);

                $text = $connection . ' (' . $time . '): ' . $fullQuery;

                if ($terminal) {
                    dump($text);
                }

                if ($log) {
                    Log::info($text);
                }
            });
        }
    }
```
This function exist in `app/Port/Provider/Traits/PortServiceProviderTrait.php` feel free to update it manually.

And the function is being used by `app/Port/Provider/Traits/PortServiceProviderTrait.php` like this `$this->debugDatabaseQueries(true, true);`

Let me know if you need any help.
