### ISSUE TITLE
Simplest way to completely disable a container

### ISSUE THREAD

**Issue by denizdogan** [Mahmoudz/Hello-API#59]
There's several parts of Hello API which I will probably never use, but I'd like to keep them just for reference, since the included containers make for very good examples.

What is the simplest way to "disable" one of the included containers, for example Paypal? So that no Paypal routes are registered, no Paypal API documentation, etc.

**Comment by Mahmoudz** [comment]
@denizdogan that's a perfect question, I actually had an old feature to enable containers.., but then removed it to load all containers by default in order to make things much faster. 

So far the best and easiest way to achieve that is by putting all the unwanted containers in and extra another folder.

```
- app
--- containers
----- containerA
----- containerB
--- examples << rename it anything
----- unwanted containerA << Paypal
----- unwanted containerB
--- port
```
